### ISSUE TITLE
Incorrect context data mapped to AA Image Request

### ISSUE THREAD

**Issue by prateekkej** [adobe/aepsdk-analyticsedge-android#9]
https://github.com/adobe/aepsdk-analyticsedge-android/blob/b9fab9c9be2c4bdacec3e34ea23eb25e703629df/code/analyticsedge/src/phone/java/com/adobe/marketing/mobile/AnalyticsExtension.java#L324

Hi Team,

This line stringifies the event data instead of context data put by the user in trackState/trackAction making the context data mapping in processing rules ineffective. 

Example,

```
// This payload will be flattened and put into "c" variable of AA request.
Event Data = {
      "contextdata":{
                 "app.name":"Something"
                             },
       "action":"Button Click!"
} 

//Instead of this,
"contextdata" : {"app.name":"Something"}

// Resulting in an output,

c : {
     "contextdata":"{app.name=Something}",
     "action":"Button Click!"
}
```

For reference, 
![image](https://user-images.githubusercontent.com/4922162/106285913-0df33f00-626b-11eb-8547-fc8c35dd0803.png)

**Comment by rymorale** [comment]
Thanks for the heads up @prateekkej. We will get this fixed and release a new build.

**Comment by rymorale** [comment]
Hi @prateekkej , thanks for the heads up. We will get this fixed and will release a new build.

**Comment by rymorale** [comment]
Hi @prateekkej, analytics edge 1.0.0 beta 6 has been released for android which resolves this issue.
